[config]
schemaVersion = "0.0.1"

[package]
namespace = "JevMods"
name = "BetterGrapplingHook"
versionNumber = "1.0.6"
description = "Tired of your grappling hook pulling you halfway through or not pulling at all? Tired of slipping off the surface every time you reach it or having to manually retrieve the anchor? This mod is for you! Heavily inspired by Just Cause game series."
websiteUrl = "https://github.com/JevMods/BetterGrapplingHook"
containsNsfwContent = false

[package.dependencies]
denikson-BepInExPack_Valheim = "5.4.2351"

[build]
icon = "./package/icon.png"
readme = "./README.md"
outdir = "./dist"

[[build.copy]]
source = "./src/BetterGrapplingHook/bin/Release/BetterGrapplingHook.dll"
target = "/"

[[build.copy]]
source = "./package/CHANGELOG.md"
target = "/"

[publish]
repository = "https://thunderstore.io"
communities = [ "valheim" ]

[publish.categories]
valheim = [ "mods", "tweaks", "client-side" ]
