[config]
schemaVersion = "0.0.1"

[package]
namespace = "JevMods"
name = "BetterGrapplingHook"
versionNumber = "1.0.3"
description = "The vanilla grappling hook often stops short of the anchor and then lets you slide down the wall. This mod gets you all the way there with a lift-off at the start, and you hang below the hook until you let go."
websiteUrl = "https://github.com/JevMods/BetterGrapplingHook"
containsNsfwContent = false

[package.dependencies]
denikson-BepInExPack_Valheim = "5.4.2351"

[build]
icon = "./package/icon.png"
readme = "./README.md"
outdir = "./dist"

[[build.copy]]
source = "./src/BetterGrapplingHook/bin/Release/BetterGrapplingHook.dll"
target = "/"

[[build.copy]]
source = "./package/CHANGELOG.md"
target = "/"

[publish]
repository = "https://thunderstore.io"
communities = [ "valheim" ]

[publish.categories]
valheim = [ "mods", "tweaks", "client-side" ]
